### ISSUE TITLE
Missing language zh-yue (Cantonese)

### ISSUE THREAD

**Issue by yipmc** [pndurette/gTTS#110]
Reading the changelog zh-yue (Cantonese) should be available as language since 1.0.4, however I'm using 2.0.0 and Cantonese seems to be missing. It doesn't show up under 'gtts-cli --all', also gtts with a 'ValueError: Language not supported' when trying to set 'zh-yue' as language.

**Comment by pndurette** [comment]
It became available in `1.0.4` but Google unfortunately removed it some time later. I'm mot sure why. I hope it comes back eventually.

The reason it's not mentioned in the `2.0.0` changeling is because a lot of language changes happened and will keep happening, `gtts-cli --all'` always gets the latest list from Google.

**Comment by hanguoyutou** [comment]
the latest version that supports Cantonese is 1.2.2
https://pypi.org/project/gTTS/1.2.2/
but it raised errors when I tried to set language == zh-yue however
