### ISSUE TITLE
"gtts.tts.gTTSError: 500 (Internal Server Error) from TTS API"

### ISSUE THREAD

**Issue by badripatro** [pndurette/gTTS#114]
Hi, 
I am trying to convert text to speech and getting following error,

----------------------------------------------------------------------------------------------------

tts.save('../train2014_ans/'+str(d[i]['ques_id'])+'.mp3')
  File ".local/lib/python2.7/site-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/home/badripatro/.local/lib/python2.7/site-packages/gtts/tts.py", line 221, in write_to_fp
    raise gTTSError(tts=self, response=r)
**gtts.tts.gTTSError: 500 (Internal Server Error) from TTS API.** Probable cause: Uptream API error. Try again later.

--------------------------------------------------------------------------------------------------------------

**Comment by pndurette** [comment]
Can you give me more details? Are you doing a lot of requests and it started doing this suddenly?

There's a fat chance that this is happening because you are hammering the Google API with your requests, so Google automatically blocked you (temporarily) from this endpoint. I suggest maybe adding some sleeps between requests (or using a different TTS engine).

**Comment by pndurette** [comment]
Let me know if this still doesn't work for you! Closing for now.
