### ISSUE TITLE
What are the limits

### ISSUE THREAD

**Issue by Fogapod** [pndurette/gTTS#117]
What are the safe limits for using lib after which Google can ban ip?

**Comment by pndurette** [comment]
I never testing this myself, could be an interesting experiment... But then again I want to anger the Google Gods the least I can.

**Comment by pndurette** [comment]
This could be an interesting thing to add to prevent people from locking themselves il (and angering the google gods).

**Comment by scivision** [comment]
I hit the limits sometimes when testing. With the new formal Google API, the quotas are high enough to not likely be an issue for many use cases.

https://cloud.google.com/text-to-speech/quotas

**Comment by dcmoss87** [comment]
I know this is old, but I also got the 429 error last night while testing. I don't believe I went even near the quota, but plan to wait a day to see if it clears. Any other suggestions would be appreciated as I'm fairly new to using gTTS as well.

**Comment by snakers4** [comment]
> I hit the limits sometimes when testing.

Hi,

If you do not want to support the corporate overlords, you can use open, high-quality third-party TTS that runs locally on one CPU core - https://github.com/snakers4/silero-models#text-to-speech

> This could be an interesting thing to add to prevent people from locking themselves out (and angering the google gods).

I doubt that this will be taken down like `pytube` but depending on the good will of corporations is not a very good idea to piggy-back on their solutions - because one day they will shut-down inevitably

**Comment by h2210316651** [comment]
> I hit the limits sometimes when testing. With the new formal Google API, the quotas are high enough to not likely be an issue for many use cases.
> 
> https://cloud.google.com/text-to-speech/quotas

Bruh, the project clearly states it's not linked with Google cloud TTS
