### ISSUE TITLE
Converting File error

### ISSUE THREAD

**Issue by arshpreetsingh** [pndurette/gTTS#12]
I am trying to convert txt file into mp3 :

gtts-cli.py -f '/home/metal-machine/Desktop/honey.txt' hello.mp3

but it is showing error "Service unavailable":

503 Server Error: Service Unavailable

**Comment by pndurette** [comment]
Hi @arshpreetsingh, unfortunately this is out of my control. It _will_ sometimes do this, when the usage is high. This Google API is open and unrestricted. When the library gets a 503, this means that there's a captcha (when on the Web), which of course this script can't deal with in its current state.

**Comment by arshpreetsingh** [comment]
Usage was not High, My text file just contained one line, But it is working right now, Can you tell me charater limit that Google allow so We can create a new feature  something like every line of file will be converted into List of string and using "loop" we can create many mp3 and after that join all of the created files? My ultimate goal is to use this library with Kivy to create "pdf to mp3" converter.

**Comment by s4chin** [comment]
He meant the usage of the Google Translate API was high, and its not because of only you. Google allows 100 characters at a time. This library already does what you are saying. If your text file contains 50 lines, the output will be the reading of **all** the lines. All of this can be found in the source. The conversion won't always work due to the above mentioned error and it is **not** the library's fault.

**Comment by sciguy14** [comment]
For what it's worth, I had the same issue - about 10% of the time I get a 503 error. I've dealt with it by adding a try/except, and falling back to the voicerss api (http://www.voicerss.org/) when gTTS gives me a 503. The speech quality is not quite as good, but it's better than nothing.
