### ISSUE TITLE
Japanese wa and ha mixup

### ISSUE THREAD

**Issue by deeredman1991** [pndurette/gTTS#149]
Pronounces "ha" as "wa" in はい(hai) even though it's not being used as a particle in this instance.

A solution could be to add a special rule to pronounce "は” characters as "ha" if it is the very first letter in a sentence (i.e. if the previous character was nothing or "。") as starting a sentence with "はい” is relatively common but starting a sentence with a particle typically isn't done (as far as I know).

This would also allow us to force a "wa" to be a "ha" just by placing a "。” if we need to in certain situations as we can always force a "wa" with わ but we have no way to force a "ha" (as far as I know)

Forcing a "wa" or "ha" with typically unused characters like "\は" and "/は" would be nice too because we could store our data to be pronounced as \ or / but we could parse those out easily before displaying them on the screen since you wont find them in too many Japanese sentences. I think just about any roman character other than "w" would be fine to use too but don't quote me on that.

**Comment by pndurette** [comment]
Hi, thanks for this! 
First I want to ask if that’s an issue that also exists on http://translate.google.com?

If not then it’s a tokenizing issue. And you’re sorta telling me how to make a rule for it, but it looks quite specific. Sorry it’s not my language so it’s hard for me to conceptualise exactly what the issue is. 

But let me know if you encounter the same issue on the Google Translate site (when you ask it to pronounce) and we will take it from there.

**Comment by xenophod** [comment]
I just tested "わたしははるです"  and は it is pronounced correctly as "wa".
I also tested "はしる", "はなせる" and "はな". In all cases は is pronounced correctly as "ha".

I'm guessing it's not an issue anymore?

**Comment by pndurette** [comment]
I'm glad to hear. Perhaps a change with the API? I'm glad since not being a Japanese speaker, it was hard for me to debug this.

Anyone please feel free to reopen this if this is still an issue!
