### ISSUE TITLE
gTTS failed while language code contains `-` 

### ISSUE THREAD

**Issue by lucemia** [pndurette/gTTS#263]
```
(venv) ➜  gtts-cli --lang zh-cn 天氣好 --output hello.mp3
Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'zh-cn'
(venv) ➜  gtts-cli --lang zh-CN 天氣好 --output hello.mp3
Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'zh-cn'
(venv) ➜  gtts-cli --lang zh-cn 天氣好 --output hello.mp3
Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'zh-cn'
(venv) ➜  gtts-cli --lang pt-br 天氣好 --output hello.mp3
Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'pt-br'
(venv) ➜ gtts-cli --lang pt-br aa --output hello.mp3
Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'pt-br'
(venv) ➜  gtts-cli --lang fr-ca aa --output hello.mp3
Error: 200 (OK) from TTS API. Probable cause: No audio stream in response. Unsupported language 'fr-ca'
(venv) ➜  gtts-cli --lang fr aa --output hello.mp3  (No Error)
```

Looks like google translate api become case sensitive. It only accept `zh-TW` instead of `zh-tw` now. So the following line need to fix.
 
https://github.com/pndurette/gTTS/blob/b36103df89e940b8d6c0cd744c341f80205815cb/gtts/tts.py#L146-L148

**Comment by cyberGhoulK** [comment]
I don't think the case matters here. I am also experiencing the same problem now. Any language mentioned with the '-' i.e. the special langs cause the error shown by @lucemia 
But replacing 'lang.lower()' with 'lang' still gives same error. So, the case is not the problem.
Hope it gets sorted out at earliest.

**Comment by mikegogulski** [comment]
I was using en-ie, changed it to en-IE, that didn't work, tried en-GB, still failed, but "en" by itself does work.

**Comment by cyberGhoulK** [comment]
I think bug label should be added to this issue.

**Comment by pndurette** [comment]
Indeed, looks like an issue with the case of the language strings. Will look into it this weekend!

**Comment by Gnome-py** [comment]
can confirm, this and #259 make gtts pretty much useless right now for my usage (a Discord TTS Bot)

**Comment by cyberGhoulK** [comment]
@pndurette So, is there any way we can access those decrepated languages(the geo variants) now? I think the old api is still up for the decrepated languages, is that the only way? Or.. is there a new method for accessing these?

**Comment by pndurette** [comment]
@cyberGhoulK Hi, that's a good question :|

I have no idea, if someone finds a way or other codes that work, I'd like to know.
That's why I added a way to "bypass" the fallback (e.g. force a language) in case some others are found..

I've heard from a user in Brazil who said that `pt` actually sounded like `pt-br` to him, so I was wondering if this was base on location of the IP, but I wasn't a able to replicate. I did a test actually where I spun up VMs all around the globe in English locales (US, UK, Australia) but `en` always sounded the same.

**Comment by cyberGhoulK** [comment]
@pndurette I think the brazil user you mentioned is right to some extent... In india, for 'en',  'en-IN' is recieved... I guess only selected regions recieve it. I also tried to change the tlds according to the regions, and i did find some variations (I tried only for 'en') , but i wasn't able to label them... I mainly searched for my requirement (en-US) by using tld as 'us'(instead of 'com') but as you tried with VMs; US, UK and Australia did remain same.

**Comment by pndurette** [comment]
@cyberGhoulK oh that's interesting! Let me know if you find anything else!

Sadly, if it's related it request location, it'll be hard to fake.

I'll try around myself with TLDs.
