### ISSUE TITLE
No pauses if 100 characters limit

### ISSUE THREAD

**Issue by Rom888** [pndurette/gTTS#396]
Great project!
Is it possible that gtts does not make audio pauses between tokens if those tokens were created due to the 100 characters limit?

**Comment by pndurette** [comment]
Hi @Rom888, that's a though one!
So the upstream API will introduce a break after 100 characters and there's no way to control this. Which is why gTTS tries to pre-emptively split (tokenize) where pauses would naturally occur (e.g. punctuation) to remediate this, which works pretty well most of the time. But if your input is more than 100 characters w/o any break that gTTS' tokenizer could use to split on, there will have a break no matter what.

**Comment by Rom888** [comment]
Here is an example:

split-string-1 <split by tokenizer>
split-string-2 <split by tokenizer>
split-string-3 <split by minimizer (because larger than 100 characters)>
split-string-4 <split by tokenizer>

If I understand correctly, gTTS gets all the split strings, makes audio, and then joins all audio fragments into one and adds pauses between audio fragments.

Is it possible to not add pauses between audio fragments 3 and 4 when join?

**Comment by pndurette** [comment]
@Rom888 Sorry for the delay—

So what you said is almost correct. gTTS splits the strings (where the speech would typically pause), then generate that audio, and puts the audio bits together. It doesn't add any breaks in the audio because it doesn't have to. It's only the natural break happening between the end of an audio phrase and the next.

So to answer your question, it's not something we can easily control other than by changing the text that is sent, i.e. with some punctuation, to make it sound at least more natural.

**Comment by Rom888** [comment]
Okay, do you think we can add an option to gtts-cli, for example:
--cut-if-minimizer=500ms
and cut the end of the audio, if that audio was because of minimizer?
(the audio from split-string-3 in the example above).

**Comment by pndurette** [comment]
Sorry for the delay—
Hmm, that would be pretty hard. Pretty much the same conclusion of what I wrote in #398:
https://github.com/pndurette/gTTS/issues/398#issuecomment-1491326989
