### ISSUE TITLE
Add support for custom sounds (beep) and other controls like pause and speed

### ISSUE THREAD

**Issue by shivaramkrs** [pndurette/gTTS#41]
I am building an application where I take documents and convert it to audio. I need a "beep" after every document. I can do it manually by appending mp3 files but it would be nice to include this in the conversion text. 
Eg: `"[[Speed=0.75]] I like weather today [[beep]] [[pause=1]]. [[Speed=0.5]] Do you like it too?"`

**Comment by juha-h** [comment]
Yes, in some cases two words come too close to each other and it would thus be nice if some pause could be introduced between them.  Some people have suggested several dots followed by space, but it does not work.  One possibility is to split the input on some marker and then combine the pieces with pause between them.

**Comment by pndurette** [comment]
Hi, sorry for the crazy delay on this! I'm reviewing past open issues that were more feature requests than bugs.

-  **Speed**: I found out recently that this [undocumented] API does have a parameter for speed. I plan to implement this in the next big release.
-  **Beep**: For now the goal of this tool is to provide an interface for the Google API and nothing more, pausing and beeps are AFAIK, not part of that API. Also a beep is very arbitrary. 
- **Pause**: Same reason as above. The only possible thing would be to add an parameter to add arbitrary pauses before or after a sound file, so nothing in the middle as both of you suggest.

(And even if I would to do it, I don't think it's doable in a way you would expect because since I do not control the speech engine on Google's side, I could not guarantee how natural it would sound (as in, someone pausing speech either with a silence or a beep) or that it would work in every language.)

**Comment by juha-h** [comment]
Pierre-Nick Durette writes:

> -  **Beep**: For now the goal of this tool is to provide an interface
> -  **for the Google API and nothing more, pausing and beeps are AFAIK,
> -  **not part of that API. Also a beep is very arbitrary.

I wrote a small python script that splits the input text on # chars and
replaces each of them with a file containing 100ms of silence and
finally then combines all pieces together to a single output file.

-- Juha

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released, adding speed (normal and slow).
