### ISSUE TITLE
gtts_cli breaks when text starts with '-'

### ISSUE THREAD

**Issue by arainflake** [pndurette/gTTS#419]
## Prerequisites
* [x] Did you make sure a similar [issue](../) didn't exist?
* [x] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

## Current Behaviour (steps to reproduce)

```
> gtts-cli "-face" -o ham.wav

Usage: gtts-cli [OPTIONS] <text>
Try 'gtts-cli -h' for help.

Error: Invalid value for '-f' / '--file': 'ace': No such file or directory

```
![image](https://github.com/pndurette/gTTS/assets/74027698/c4f76035-23a5-47da-bbae-72f6518832b7)
![image](https://github.com/pndurette/gTTS/assets/74027698/2e2199f1-95d4-4beb-b6b0-2d633ffc6e14)

## Expected Behaviour
It should be expected to interpret the text as a solid block of text and not brake it into multiple arguments.

```
gtts-cli "-face" -o test.wav
```
would expect the above to output an audio file saying "minus face" or "dash face"

## Context
trying to use the g_tts library through the command line helper (gtts-cli), and noticed that the command line parser breaks when the inline text starts with a '-' such as "-hello" or "-face" it seems to interpret it as "-f" and "ace" as seperate arguments. if using "-hello" it sees "-h" as a proper argument, and then says "e" is not a valid option. 

## Environment
gtts version: 2.3.2
os is manjaro with the i3 window manager, fish and bash shell tested

**Comment by pndurette** [comment]
Sorry for the huge delay on this! This is indeed quite a bug, it takes `-face` as `-f ace`.

**Comment by pndurette** [comment]
First of all, thanks for all the details.
So, it's been taking a while because I've been dabating this. I've also been searching this, and I don't think I can easily fix this.

There's been quite a lot of debate about fixing or not that issue when it happened with Python's `argparse` [more than 10 years ago now](https://bugs.python.org/issue9334), it resulted in a 'wont fix'

My suggestions of workarounds:
* Add a space: `gtts-cli ' -face' -l en --output test1.mp3`
* Escape the dash: `gtts-cli '\-face' -l en --output test1.mp3`
* Use the library itself (not the cli) to write Python code, instead of scripting with `gtts-cli`.

**Comment by arainflake** [comment]
much appreciated for the advice. Ill go with those options.
