### ISSUE TITLE
GTTS is adding in a word when speaking.

### ISSUE THREAD

**Issue by dermotgouk** [pndurette/gTTS#447]
## Prerequisites
* [x] Did you make sure a similar [issue](../) didn't exist?
* [x] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

## Current Behaviour (steps to reproduce)
GTTS is speaking the following sentence and after the number 4 its adding a word that sounds like feat/feed/feet
('Space 4 ', 'RS027', 'Operational', 'Space 4 ')
```
                finished = ("Space 4","RS027","Operational","Space 4")
                finishing =str(finished)
                print(finishing)
                var= gTTS(text = finishing,lang = 'en') 
                var.save('eng.mp3')
```

## Expected Behaviour
It should not add this additional word afterwards 
```
code
```

## Context
Space 4 is called from a variable which parses an array list for the index.

## Environment

* gTTS version: 2.3.1
* Operating System version: Windows 10

**Comment by pndurette** [comment]
@dermotgouk Ah, I see why.

So when you're transforming your tuple to string (with `str(finished)`), it actually creates the string `('Space 4', 'RS027', 'Operational', 'Space 4')`

The last `'` is read like "feet" as in the imperial measurement, most likely because this is how Google reads `'` when it comes after a number, e.g. `6'` (six feet). It does the same on the first `space 4` in string as well.

If you really want it to read a list verbatim, I'd use a `join()`, i.e.:

```python
finished = ("Space 4", "RS027", "Operational", "Space")
finishing = ", ".join(finished)
print(finishing)
var = gTTS(text=finishing, lang="en")
var.save("eng.mp3")
```

That way it'll read `'Space 4, RS027, Operational, Space 4`
