### ISSUE TITLE
proxy and encode process

### ISSUE THREAD

**Issue by common83** [pndurette/gTTS#45]
sometimes ,we need proxy and also should change the encode type.

here is my way:
https://github.com/common83/gtts_with_proxy

**Comment by pndurette** [comment]
Hi, sorry for the crazy delay on this! I'm reviewing past open issues that were more feature requests than bugs. Also thanks for the `ttsspeed`, I didn't know about that. I will implement that.

As for using Web proxies and encoding, it's also planned. Probably in the next big release.

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released. It passes the system proxies transparently using `urllib.request.getproxies()` without having to specifically define them.

**Comment by seriadiallo** [comment]
I think the best way might be giving the possibility to give the proxy configs as parameter to the function gTTS

**Comment by pndurette** [comment]
You shouldn't need to do this anymore, since gTTS will just read what's defined. [`urllib` will pass along any proxies you have defined as `*_poxy` environment variable](https://docs.python.org/3/library/urllib.request.html#module-urllib.request)

 Some examples here: https://www.cyberciti.biz/faq/linux-unix-set-proxy-environment-variable/
