### ISSUE TITLE
Missing punctuation

### ISSUE THREAD

**Issue by eric-s-s** [pndurette/gTTS#86]
Hello,

While looking through [this question](https://stackoverflow.com/questions/47564452/recursionerror-when-using-gtts-on-python) , I was looking at the punctuation in your code and the chinese language test in your tests.  The Chinese comma (`"，"`) seems to missing from the punctuation in `_tokenize`, [here](https://github.com/pndurette/gTTS/blob/b48e7a5d7bbcff1b00003d8b3b6fda8ddd6b69d0/gtts/tts.py#L162). Since Chinese rarely uses periods or spaces, it was entirely possible that he was getting a maximum recursion error by have a space with a combination of 99 characters and commas.  I thought I would let you know as I can't imagine the fix requires more than inserting that one character into the list.

**Comment by pndurette** [comment]
Sorry for the super long delay about this, but I wanted to thank you a lot for this. I had not seen the original issue (I should set a watch on SO), but I'm currently refactoring a lot of gTTS and this dragged me down quite an interesting rabbit hole and deeper underlying issues (which are fixed for the upcoming `2.0.0`. I added the Chinese comma too! (but the problem was deeper than that!)

**Comment by eric-s-s** [comment]
glad to hear it was helpful!

**Comment by pndurette** [comment]
gTTS `2.0.0` was released and should fix this! 👍
